#
# Makefile for src/man (man page tree)
#

TOP=..
.include "$(TOP)/mk/os161.config.mk"

SUBDIRS=bin sbin testbin libc syscall dev misc

# Top level man pages
MANDIR=/man
MANFILES=index.html man.css manindex.css

.include "$(TOP)/mk/os161.subdir.mk"
.include "$(TOP)/mk/os161.man.mk"

