# Man pages for device drivers

TOP=../..
.include "$(TOP)/mk/os161.config.mk"

MANDIR=/man/dev
MANFILES=\
	beep.html con.html emu.html index.html lamebus.html lhd.html \
	lnet.html lrandom.html lscreen.html lser.html ltimer.html \
	null.html random.html rtclock.html

.include "$(TOP)/mk/os161.man.mk"

