#
# Makefile for src/lib (sources for libraries installed in /lib)
#
# Note that all includes are found in src/include - the "includes"
# make rule for installing .h files does not come here.
#

TOP=../..
.include "$(TOP)/mk/os161.config.mk"

SUBDIRS=crt0 libc libtest libtest161 hostcompat

.include "$(TOP)/mk/os161.subdir.mk"
