# Makefile for hash

TOP=../../..
.include "$(TOP)/mk/os161.config.mk"

PROG=hash
SRCS=hash.c
BINDIR=/testbin
HOSTBINDIR=/hostbin

.include "$(TOP)/mk/os161.prog.mk"
.include "$(TOP)/mk/os161.hostprog.mk"

