# Makefile for frack

TOP=../../..
.include "$(TOP)/mk/os161.config.mk"

PROG=frack
SRCS=main.c workloads.c ops.c do.c check.c pool.c data.c name.c
BINDIR=/testbin

.include "$(TOP)/mk/os161.prog.mk"

