# Makefile for mksfs

TOP=../../..
.include "$(TOP)/mk/os161.config.mk"

PROG=mksfs
SRCS=mksfs.c disk.c support.c
BINDIR=/sbin
HOSTBINDIR=/hostbin


.include "$(TOP)/mk/os161.prog.mk"
.include "$(TOP)/mk/os161.hostprog.mk"
