# Man pages for system calls

TOP=../..
.include "$(TOP)/mk/os161.config.mk"

MANDIR=/man/syscall
MANFILES=\
	__getcwd.html __time.html _exit.html chdir.html close.html dup2.html \
	errno.html execv.html fork.html fstat.html fsync.html ftruncate.html \
	getdirentry.html getpid.html index.html ioctl.html link.html \
	lseek.html lstat.html mkdir.html open.html pipe.html read.html \
	readlink.html reboot.html remove.html rename.html rmdir.html \
	sbrk.html stat.html symlink.html sync.html waitpid.html write.html

.include "$(TOP)/mk/os161.man.mk"

