# Makefile for psort

TOP=../../..
.include "$(TOP)/mk/os161.config.mk"

PROG=psort
SRCS=psort.c
BINDIR=/testbin
HOSTBINDIR=/hostbin

.include "$(TOP)/mk/os161.prog.mk"
.include "$(TOP)/mk/os161.hostprog.mk"

