#
# libtest - library of common test support code
#

TOP=../../..
.include "$(TOP)/mk/os161.config.mk"

COMMON=$(TOP)/common/libtest161

SRCS+=\
	$(COMMON)/secure.c \
	$(COMMON)/sha256.c \
	$(COMMON)/test161.c \

LIB=test161

.include  "$(TOP)/mk/os161.lib.mk"
