# Man pages for /sbin programs

TOP=../..
.include "$(TOP)/mk/os161.config.mk"

MANDIR=/man/sbin
MANFILES=dumpsfs.html halt.html index.html mksfs.html poweroff.html reboot.html

.include "$(TOP)/mk/os161.man.mk"

