# Man pages for libraries

TOP=../..
.include "$(TOP)/mk/os161.config.mk"

MANDIR=/man/libc
MANFILES=\
	__vprintf.html abort.html assert.html atoi.html bzero.html \
	calloc.html err.html exit.html free.html getchar.html getcwd.html \
	index.html malloc.html memcpy.html memmove.html memset.html \
	printf.html putchar.html puts.html random.html realloc.html \
	setjmp.html snprintf.html stdarg.html strcat.html strchr.html \
	strcmp.html strcpy.html strerror.html strlen.html strrchr.html \
	strtok.html strtok_r.html system.html time.html warn.html

.include "$(TOP)/mk/os161.man.mk"

