# Makefile for usemtest

TOP=../../..
.include "$(TOP)/mk/os161.config.mk"

PROG=usemtest
SRCS=usemtest.c
BINDIR=/testbin
HOSTBINDIR=/hostbin

.include "$(TOP)/mk/os161.prog.mk"
.include "$(TOP)/mk/os161.hostprog.mk"

