#
# Makefile for src/sbin (sources for programs installed in /sbin)
#

TOP=../..
.include "$(TOP)/mk/os161.config.mk"

SUBDIRS=reboot halt poweroff mksfs dumpsfs sfsck

.include "$(TOP)/mk/os161.subdir.mk"
