# Man pages for /testbin programs

TOP=../..
.include "$(TOP)/mk/os161.config.mk"

MANDIR=/man/testbin
MANFILES=\
	add.html argtest.html badcall.html bigfile.html conman.html \
	crash.html ctest.html dirseek.html dirtest.html f_test.html \
	farm.html faulter.html filetest.html forkbomb.html forktest.html \
	guzzle.html hash.html hog.html huge.html index.html kitchen.html \
	malloctest.html matmult.html palin.html randcall.html rmdirtest.html \
	rmtest.html sink.html sort.html sty.html tail.html tictac.html \
	triplehuge.html triplemat.html triplesort.html userthreads.html

.include "$(TOP)/mk/os161.man.mk"

